trigger:
  branches:
    include:
      - dev
pool:
  vmImage: 'windows-latest'

variables:
  # Setup the environment-specific backend files and variable files
  terraformBackendFile: ''
  terraformVarFile: ''
  terraformPlan: ''

stages:
  - stage: Build
    displayName: 'Terraform Build'
    jobs:
      - job: Terraform_Init_Validate
        displayName: 'Terraform Init and Validate'
        steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - script: |
              echo "Branch Name: $(Build.SourceBranchName)"
              if [[ "$(Build.SourceBranchName)" == "dev" ]]; then
                echo "Setting variables for Dev environment..."
                echo "##vso[task.setvariable variable=terraformPlan]dev.tfplan"
                echo "##vso[task.setvariable variable=terraformBackendFile]dev.tfstate"
                echo "##vso[task.setvariable variable=terraformVarFile]Environments/Development/dev.tfvars"
              elif [[ "$(Build.SourceBranchName)" == "staging" ]]; then
                echo "Setting variables for Staging environment..."
                echo "##vso[task.setvariable variable=terraformPlan]staging.tfplan"
                echo "##vso[task.setvariable variable=terraformBackendFile]staging.tfstate"
                echo "##vso[task.setvariable variable=terraformVarFile]Environments/Staging/stage.tfvars"
              elif [[ "$(Build.SourceBranchName)" == "main" ]]; then
                echo "Setting variables for Production environment..."
                echo "##vso[task.setvariable variable=terraformPlan]prod.tfplan"
                echo "##vso[task.setvariable variable=terraformBackendFile]prod.tfstate"
                echo "##vso[task.setvariable variable=terraformVarFile]Environments/Production/prod.tfvars"
              fi
            displayName: "Set Variables for Environment"
          # Initialize Terraform
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'ARM'
              backendAzureRmResourceGroupName: 'terraform-state-rg'
              backendAzureRmStorageAccountName: 'tfstatestoragecloud'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '$(terraformBackendFile)'
            displayName: 'Terraform Init'
          # Validate Terraform Code
          - script: |
              terraform validate
            displayName: 'Terraform Validate'
          # Package Terraform files (Create plan)
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-var-file=$(terraformVarFile)'
              environmentServiceNameAzureRM: 'ARM'
            displayName: 'Terraform Plan'
          - publish: $(Build.SourcesDirectory)/
            artifact: '$(terraformPlan)'
            displayName: 'Publish Plan Artifacttf_version'
            
          # Sonar Cloud Code Analysis
          - task: SonarCloudPrepare@3
            inputs:
              SonarQube: 'Sonar Cloud'
              organization: 'vaibhavmahna270908'
              scannerMode: 'other'
          - task: SonarCloudAnalyze@3
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'
          
          - task: SonarCloudPublish@3
            inputs:
              pollingTimeoutSec: '100'
