trigger:
  branches:
    include:
      - dev
      - staging
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Set environment-specific backend files and variable files
  terraformBackendFile: ''
  terraformVarFile: ''

stages:
  - stage: Build
    displayName: 'Terraform Build'
    jobs:
      - job: Terraform_Init_Validate
        displayName: 'Terraform Init and Validate'
        steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - script: |
              echo "Branch Name: $(Build.SourceBranchName)"
              if [[ "$(Build.SourceBranchName)" == "refs/heads/dev" ]]; then
                echo "Setting variables for Dev environment..."
                echo "vso[task.setvariable variable=terraformBackendFile]backend-dev.tfbackend"
                echo "vso[task.setvariable variable=terraformVarFile]dev.tfvars"
              elif [[ "$(Build.SourceBranchName)" == "refs/heads/staging" ]]; then
                echo "Setting variables for Staging environment..."
                echo "vso[task.setvariable variable=terraformBackendFile]backend-staging.tfbackend"
                echo "vso[task.setvariable variable=terraformVarFile]stage.tfvars"
              elif [[ "$(Build.SourceBranchName)" == "refs/heads/main" ]]; then
                echo "Setting variables for Production environment..."
                echo "vso[task.setvariable variable=terraformBackendFile]backend-prod.tfbackend"
                echo "vso[task.setvariable variable=terraformVarFile]prod.tfvars"
              fi
            displayName: "Set Variables for Environment"
          # Initialize Terraform
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'ARM'
              backendAzureRmResourceGroupName: 'terraform-state-rg'
              backendAzureRmStorageAccountName: 'tfstatestoragecloud'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'development.tfstate'
            displayName: 'Terraform Init'
          # Validate Terraform Code
          - script: |
              terraform validate
            displayName: 'Terraform Validate'
          # Package Terraform files (Create plan)
          - script: |
              terraform plan -var-file=$(terraformVarFile) -out=tfplan
            displayName: "Terraform Plan"

          - publish: $(Build.SourcesDirectory)/
            artifact: tfplan
            displayName: 'Publish Plan Artifacttf_version'
